### ISSUE TITLE
tokenless usage

### ISSUE THREAD

**Issue by MathildaSu** [esoreq/dcarte#12]
Is there a way to add a token into my code somewhere, or save it in a file, so when starting up I don't get the token promt but use the already provided token directly?

**Comment by esoreq** [comment]
What do you mean?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ting Su ***@***.***>
Sent: Tuesday, August 16, 2022 1:55:04 PM
To: esoreq/dcarte ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esoreq/dcarte] tokenless usage (Issue #12)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Is there a way to add a token into my code somewhere, or save it in a file, so when starting up I don't get the token promt but use the already provided token directly?

**Comment by MathildaSu** [comment]
it usually prompts for the login token when i load (because i use a container), but it's a bit tricky to put in the token when deploying the container to azure. 
So i wonder if i can added it in the code so that it automatically login.

**Comment by esoreq** [comment]
Oh so within the container this would require some adjustments.
We need to chat - perhaps next week

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MathildaSu** [comment]
I think there might be a workaround with this. 
can we add a line to check if there is a environment viriable to use before asking to input the token? I can update the env regularly to reflect the token update. 
Such as: 
```
try:
    toekn = os.getenv('DCARTE_TOKEN')
```

**Comment by esoreq** [comment]
Why not use the environment token dcarte sets ?
os.getenv('MINDER_TOKEN')
________________________________

**Comment by MathildaSu** [comment]
Oh i didn't notice it was already there. i will simply set that then. thank you

**Comment by MathildaSu** [comment]
fixed in https://github.com/esoreq/dcarte/pull/13
