### ISSUE TITLE
Unable to limit data requests to specific cohorts

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/dcarte#16]
Given an access token that provides access to data from multiple cohorts it would be very helpful to be able to retrieve data for a subset of those cohorts. The server provides the `organizations` specifier for this purpose:
```json
{
        "since": "2023-02-28T00:00:00.000Z",
        "until": "2023-03-01T00:00:00.000Z",
        "datasets": {
            "raw_activity_pir": {
                "columns": [
                    "start_date",
                    "patient_id",
                    "home_id",
                    "location_id",
                    "location_name"
                ]
            }
        },
        "organizations": [
            "F3iU1mKLzpJWWG7BEQViAZ",
            "2zx3cAh81xxTuKTzXCxYDF"
        ]
    }
```
If unspecified by user then library can continue to exclude `organizations` from request, retaining current behaviour of returning data for all cohorts that token has access to.

**Comment by esoreq** [comment]
I'll add this to the todo list


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mark Woodbridge ***@***.***>
Sent: Wednesday, March 1, 2023 2:10:21 PM
To: esoreq/dcarte ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esoreq/dcarte] Unable to limit data requests to specific cohorts (Issue #16)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Given an access token that provides access to data from multiple cohorts it would be very helpful to be able to retrieve data for a subset of those cohorts. The server provides the organizations specifier for this purpose:

{
        "since": "2023-02-28T00:00:00.000Z",
        "until": "2023-03-01T00:00:00.000Z",
        "datasets": {
            "raw_activity_pir": {
                "columns": [
                    "start_date",
                    "patient_id",
                    "home_id",
                    "location_id",
                    "location_name"
                ]
            }
        },
        "organizations": [
            "F3iU1mKLzpJWWG7BEQViAZ",
            "2zx3cAh81xxTuKTzXCxYDF"
        ]
    }

**Comment by esoreq** [comment]
This is now solved by the new minder_downloader module
