### ISSUE TITLE
dcarte.update_domain -> Exception: Sorry, environmental is not a registered dataset in raw domain in dcarte

### ISSUE THREAD

**Issue by francescapalermo** [esoreq/dcarte#17]
When running:
`dcarte.update_domain(domain='base')`

the following exception is raised:

`Exception: Sorry, environmental is not a registered dataset in raw domain in dcarte`

In this version (dcarte 0.4.6), it seems that Environmental has been deleted by RAW domain and replaced by Ambient_Temperature so update domain function should be updated as well to cover the modification.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/22662256/223701594-362e90d9-a0f4-4119-86a6-a5a9188b2b2a.png">

<img width="200" alt="image (1)" src="https://user-images.githubusercontent.com/22662256/223701586-10434cd6-9107-4500-9d2e-dc51ff075020.png">

**Comment by esoreq** [comment]
Yes I suggest updating to the new version '0.4.14'
Environmental was combining both Ambient_Temperature and Light 
If this persists it means that there is a residual of  Environmental files in the system - 
Can be dealt with using the new 
`dcarte.delete_dataset('Environmental','base')`
