### ISSUE TITLE
 doors is not a registered dataset in base domain in dcarte

### ISSUE THREAD

**Issue by francescapalermo** [esoreq/dcarte#2]
When running the base.py script, the following Exception is raised:
`Exception: Sorry, doors is not a registered dataset in base domain in dcarte
`
This seems to be due to the fact that, when looping over the parent_datasets in the create_base_datasets() function, the scripts searches for the doors dataset in the base domain configuration because of 'Entryway':[['doors','base']] in the load.py and raise the exception, even if the doors.parquet file has been created in the data/base folder.

```
Traceback (most recent call last):
  File "**test_dcarte.py**", line 5, in <module>
    base.create_base_datasets()
  File "**base.py**", line 181, in create_base_datasets
    p_datasets = {d[0]:dcarte.load(*d) for d in parent_datasets[dataset]} 
  File "**base.py**", line 181, in <dictcomp>
    p_datasets = {d[0]:dcarte.load(*d) for d in parent_datasets[dataset]} 
  File "**utils.py**", line 123, in wrapped
    out = fun(*fun_args, **fun_kwargs)
  File "**load.py**", line 41, in load
    raise Exception(f"Sorry, {dataset} is not a registered dataset in {domain} domain in dcarte")
Exception: Sorry, doors is not a registered dataset in base domain in dcarte
```

**Comment by esoreq** [comment]
Ok found the problem that caused this and fixed it 
The new version 0.3.21 should be working now
