### ISSUE TITLE
Possible bug in sleep data

### ISSUE THREAD

**Issue by francescapalermo** [esoreq/dcarte#3]
I am investigating the analysis fot eh sleep data to add to the fall detection algorithm.
When analysing the Sleep Dailies - PROFILE for patient 'B3cr4Euax91r63NSvVhrxs' on date **27/08/21**, there is a profile for that day but no data for Sleep_mat or Sleep_Event RAW or Sleep - BASE exist for the time that the person could have been in bed.\
No data corresponding to the **night of 2021-08-26** or to the **morning of 2021-08-27**.

In Sleep - BASE, the last entry around that period is for **2021-08-26** at 07:22:00.
In Sleep_Event - RAW, the last entry is on **2021-08-26** at 11:15:30 and it then returns at **2021-08-27** 23:10:48
In Sleep_Mat - RAW, the last entry is on **2021-08-26** at 06:22:00

**Comment by esoreq** [comment]
So according to my understanding sleep_event are sensor triggers (that is why they are in ms) I think they are more sensitive and as a result, could be triggered potentially by a pet - worth checking with one of the clinical team if this patient has a pet. 
I think we should ignore sleep_event for the time being and rely on the sleep_mat data that exists in the sleep base dataset - what do you think?

**Comment by francescapalermo** [comment]
Completely agree! The sleep_mat should be more reliable for creating the sleep profiles and in general for the analysis, especially considering that we don't have yet a method to distinguish among the people/animals triggering the sensors.
My main concern is how come there is a sleep profile for that specific day (27-08-21) if no data are available in the database.
Which data is the sleep profile using in this case?

**Comment by esoreq** [comment]
it's referring to the night of 27th - i.e. from 2021-08-27 12:00 - 2021-08-28 12:00 patient was in bed from 2021-08-28 01:01:00 till 2021-08-28 08:54:00

**Comment by francescapalermo** [comment]
Thank you so much! I thought the analysis was restrospective so sleep profile for 2021-08-27 12:00 corresponded to the night of 2021-08-26 until the morning of 2021-08-27
